### ISSUE TITLE
Is TVDML still active?

### ISSUE THREAD

**Issue by serchavalos** [a-ignatov-parc/tvdml#61]
Hello @a-ignatov-parc

Just checking if this project is still active and would welcome contributions, like upgrading dependencies or using TypeScript.

Cheers,

**Comment by a-ignatov-parc** [comment]
Hi @serchavalos, thanks for reaching out. I'd say this project is inactive as there aren't many people developing TVML apps with React.js and neither am I + plus I don't have much free time to support it. So please take this into account when deciding whether or not you should contribute.

If you need to make changes to your project, it's best to fork this repo and then we can figure out how to upstream your changes. If it's just for the sake of improving this project, I highly recommend not doing it, especially we're talking about adding first-class TS support, which would require a huge amount of work due to the rather large differences between the HTML and TVML. I just won't have enough time to help you.

**Comment by serchavalos** [comment]
No problem, I'll follow your suggestion then.

Thanks @a-ignatov-parc for the reply!
